[package]
name = "html-temp"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
minijinja = { version = "2.0.1", features = ["builtins"] }
serde = { version = "1.0.200", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
